-- SQLite
-- SQLite
CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    CONTRACT_DATE DATE NOT NULL,
    POSITION_ID INT,
    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(ID)
);